plugins {
    id 'org.jetbrains.intellij' version '1.17.4'
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version "1.9.0"
}

group 'tech.lin2j'
version '1.4.1-223'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.hierynomus:sshj:0.39.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.2'
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.8.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
//    version = '2022.3'
//    type = 'IU'
    plugins = [
            'com.intellij.java',
            "org.jetbrains.plugins.terminal",
    ]
    //localPath = 'D:\\Program Files\\ideaIU-2023.2.8.win'
    localPath = '/Applications/IntelliJ IDEA 2.app/Contents'
    updateSinceUntilBuild = false
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs << "-Xlint:unchecked"
}

test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(17)
}
